#pragma config(Sensor, S1,     leftSonar,           sensorSONAR)
#pragma config(Sensor, S2,     centreSonar,         sensorSONAR)
#pragma config(Sensor, S3,     rightSonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int desiredLeft = 19;

void doLeftTurn()
{
    nSyncedMotors = synchBC;
  	nSyncedTurnRatio = -100;
  	nMotorEncoderTarget[motorB] = 190;
  	motor[motorB] = -20;
  	while(nMotorRunState[motorB] != runStateIdle) {}
    nSyncedMotors = synchNone;
}

void doRightTurn()
{
    nSyncedMotors = synchBC;
  	nSyncedTurnRatio = -100;
  	nMotorEncoderTarget[motorB] = 190;
  	motor[motorB] = 20;
  	while(nMotorRunState[motorB] != runStateIdle) {}
    nSyncedMotors = synchNone;
}

void wallFollow()
{
  int leftSonarValue = SensorValue[leftSonar];
  nxtDisplayCenteredBigTextLine(1,"%d", leftSonarValue);
  int err = desiredLeft - leftSonarValue;
  nxtDisplayCenteredBigTextLine(4,"%d", err);
  if(leftSonarValue > 30)
  {
    motor[motorB] = 0;
  	motor[motorC] = 0;
  	nSyncedMotors = synchBC;
  	nSyncedTurnRatio = 100;
  	nMotorEncoderTarget[motorB] = 180;
  	motor[motorB] = 20;
  	while(nMotorRunState[motorB] != runStateIdle) {}
  	doLeftTurn();
  	nSyncedMotors = synchBC;
  	nSyncedTurnRatio = 100;
  	nMotorEncoderTarget[motorB] = 180;
  	motor[motorB] = 20;
  	nSyncedMotors = synchNone;
  }
  else
  {
    if(err > 4 && err <= 8) //ergo need to increase left motor reduce right motor
    {
  	  motor[motorB] = 21;
  	  motor[motorC] = 19;
    }
    else if(err > 8) //ergo need to increase left motor reduce right motor
    {
  	  motor[motorB] = 25;
  	  motor[motorC] = 15;
    }
    else if(err < -4 && err >= -8) //ergo need to increase left motor reduce right motor
    {
  	  motor[motorB] = 19;
  	  motor[motorC] = 22;
    }
    else if(err < -8) //ergo need to increase left motor reduce right motor
    {
  	  motor[motorB] = 15;
  	  motor[motorC] = 25;
    }
    else
    {
      motor[motorB] = 20;
  	  motor[motorC] = 20;
    }
  }

}

task main()
{
  nSyncedMotors = synchNone;
  nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;
  nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
  motor[motorB] = 20;
  motor[motorC] = 20;
  ClearTimer(T1);
  while(1)
  {
  	int centreSonarValue = SensorValue[centreSonar];
  	if(time100[T1] >= 1)
  	{
  	  wallFollow();
  		ClearTimer(T1);
  	}
  	if(centreSonarValue < 19)
  	{
  		doRightTurn();
  		motor[motorB] = 20;
  	  motor[motorC] = 20;
  	  ClearTimer(T1);
  	}
  }


}
