#pragma config(Sensor, S1,     leftSonar,           sensorSONAR)
#pragma config(Sensor, S2,     centreSonar,         sensorSONAR)
#pragma config(Sensor, S3,     rightSonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////
//      Title:- Pose Cells and local view combined
//      Author:- Lachlan Smith (RobotC)
//               Mark Wakabayashi (Java version)
//               Michael Milford (original algorithim/c code)
//      Purpose:- This is implementing pose cells and local cell together
//
//
//////////////////////////////////////////////////////////////////////////////////


//----include files----//
#include "localNeural.h";
#include "poseCell.h";
#include "math.h";
#include "experienceMap.h"

//testing writing to text files
TFileHandle hFileHandle = 0;
TFileHandle hFileHandle2 = 0;
TFileHandle hFileHandle3 = 0;
TFileIOResult nIoResult;
TFileIOResult nIoResultRead;
int nFileSize = 12000;
int nFileSize2 = 12000;
const string sFileName1 = "local1.dat";
const string sFileName2 = "local2.dat";


//----General In-Module Variables----//
int numActive = 0; //number of active cells
int currentTheta = 0; //theta for pose and turns
int currentDirection = 0; //direction for pose and turns
int changeTheta = 0;
localViewCell localTemp; //holds the temporary neural value
localViewCell localComparison; //what the local cell data is loaded into
char nextEmptyCell = 0; //used for holding the next empty cell in the localcell Struct
int encoderX = 0; //total move in x-direction in encoder clicks for experiences
int encoderY = 0; //total move in y-direction in encoder clicks for experiences
int encoderTheta = 0; //will equal change theta
char injectX = 0;
char injectY = 0;
char injectTheta = 0;
int nextID = 0; //main file
int nextLink = 0;//main file
vector3D encoderData;

//                           //
//----Pose Cell Functions----//
//                           //

//----initialises the start cell and sets starting activation----//
void startCell()
{
  poseWorld.maxActivatedCell.x = 5;
  poseWorld.maxActivatedCell.y = 5;
  poseWorld.maxActivatedCell.theta = 0;
  poseWorld.poseActivity[5].array2D[5][0] = startActivation;
}

//----initalises all pose cells as inactive and sets all pose activity to zero----//
void setupPoseStructure()
{
  memset(tempPose, 0, numberOfCells);
  memset(poseWorld,0, numberOfCells + 3);
}

//----Excitation matrix----//
void excitationMatrixSetup()
{
	//done in matlab - probably should check if right
  excitation_Weights[0].array2D[0][0] =  0.0495;
  excitation_Weights[0].array2D[0][1] =  0.3655;
  excitation_Weights[0].array2D[0][2] =  0.0495;
  excitation_Weights[0].array2D[1][0] =  0.1727;
  excitation_Weights[0].array2D[1][1] =  1.2757;
  excitation_Weights[0].array2D[1][2] =  0.1727;
  excitation_Weights[0].array2D[2][0] =  0.0495;
  excitation_Weights[0].array2D[2][1] =  0.3655;
  excitation_Weights[0].array2D[2][2] =  0.0495;

  excitation_Weights[1].array2D[0][0] =  0.1727;
  excitation_Weights[1].array2D[0][1] =  1.2757;
  excitation_Weights[1].array2D[0][2] =  0.1727;
  excitation_Weights[1].array2D[1][0] =  0.6026;
  excitation_Weights[1].array2D[1][1] =  4.4528;
  excitation_Weights[1].array2D[1][2] =  0.6026;
  excitation_Weights[1].array2D[2][0] =  0.1727;
  excitation_Weights[1].array2D[2][1] =  1.2757;
  excitation_Weights[1].array2D[2][2] =  0.1727;

  excitation_Weights[2].array2D[0][0] =  0.0495;
  excitation_Weights[2].array2D[0][1] =  0.3655;
  excitation_Weights[2].array2D[0][2] =  0.0495;
  excitation_Weights[2].array2D[1][0] =  0.1727;
  excitation_Weights[2].array2D[1][1] =  1.2757;
  excitation_Weights[2].array2D[1][2] =  0.1727;
  excitation_Weights[2].array2D[2][0] =  0.0495;
  excitation_Weights[2].array2D[2][1] =  0.3655;
  excitation_Weights[2].array2D[2][2] =  0.0495;
}

//----Clears Encoders - used to ensure correct rotation angles----//
void clearEncoders()
{
	//have to unsynch motors as when clearing the master the slave wont clear
	//and attempting to clear the slave causes an error
	nSyncedMotors = synchNone;
  nMotorEncoder[motorC] = 0;
  nMotorEncoder[motorB] = 0;
}

//----Determine rotation of robot from encoder values----//
int getRotation()
{
	float motorBCount = nMotorEncoder[motorB];
	float motorCCount = nMotorEncoder[motorC];
	motorBCount /= 190; //distance between wheels in encoder clicks
	motorCCount /= 190;
	int thetaOne;
	int thetaTwo;
	int thetaThree;
	if(motorBCount<0)
	{
	  motorBCount *= -1;
	  thetaOne = radiansToDegrees(atan(motorBCount));
	  thetaTwo = radiansToDegrees(atan(motorCCount));
    return -(thetaOne + thetaTwo);
	}
	else if(motorCCount<0)
	{
    motorCCount *= -1;
	  thetaOne = radiansToDegrees(atan(motorBCount));
	  thetaTwo = radiansToDegrees(atan(motorCCount));
	  return (thetaOne + thetaTwo);
  }
  else if(motorCCount < 0 && motorBCount < 0)
  {
  	motorBCount *= -1;
  	motorCCount *= -1;
  	thetaOne = radiansToDegrees(atan(motorBCount));
	  thetaTwo = radiansToDegrees(atan(motorCCount));
	  return (thetaOne + thetaTwo);
  }
  else
  {
  	thetaOne = radiansToDegrees(atan(motorBCount));
	  thetaTwo = radiansToDegrees(atan(motorCCount));
	  return (thetaOne - thetaTwo);
  }
  return thetaThree;
}


//----Wrapping values in x-direction in Pose structure----//
char getWrappedX(char indexX)
{
  if(indexX < 0)
  {
    return (indexX + sizeX);
  }
  else if(indexX >= sizeX)
  {
    return (indexX - sizeX);
  }
  return indexX;
}

//----Wrapping values in y-direction in Pose structure----//
char getWrappedY(char indexY)
{
  if(indexY < 0)
  {
    return (indexY + sizeY);
  }
  else if(indexY >= sizeY)
  {
    return (indexY - sizeY);
  }
  return indexY;
}

//----Wrapping values in theta-direction in Pose structure----//
char getWrappedTheta(char indexTheta)
{
  if(indexTheta < 0)
  {
    return (indexTheta + sizeTheta);
  }
  else if(indexTheta >= sizeTheta)
  {
    return (indexTheta - sizeTheta);
  }
  return indexTheta;
}

//----Sets activation in cell and handles maximum cell----//
void setActivation(char cellX, char cellY, char cellTheta, float activation)
{
	float previousActivation; //previous activation of a cell
	float maxActivation; //activation of max axtivated cell
	char maxX;  //co-ordinates of max activated cell
	char maxY;
	char maxTheta;

	//set values
  previousActivation = poseWorld.poseActivity[cellX].array2D[cellY][cellTheta];
  maxX = poseWorld.maxActivatedCell.x;
  maxY = poseWorld.maxActivatedCell.y;
  maxTheta = poseWorld.maxActivatedCell.theta;
  maxActivation = poseWorld.poseActivity[maxX].array2D[maxY][maxTheta];

  if(previousActivation == activation)
  {//if the same do nothing, exit function
    return;
  }
  poseWorld.poseActivity[cellX].array2D[cellY][cellTheta] = activation; //else set activation

  if(activation > maxActivation)
  {//if activation greater than max, then set as maximum
    poseWorld.maxActivatedCell.x = cellX;
    poseWorld.maxActivatedCell.y = cellY;
    poseWorld.maxActivatedCell.theta = cellTheta;
  }
}

//----Injects additional activity into cells----//
void injectEnergy (float stepSize, char xCell, char yCell, char thetaCell)
{
  float previousActivation = poseWorld.poseActivity[xCell].array2D[yCell][thetaCell];
  setActivation(xCell,yCell,thetaCell, previousActivation + (injectionStrength * stepSize));
}

//----Excites neighbouring cells----//
void doExcitation(float stepSize)
{
  //initialises loop varibles
  char i;
  char j;
  char k;

  char relX;
  char relY;
  char relTheta;

  memcpy(tempPose, poseWorld.poseActivity, numberOfCells); //fillTempPose();

  for(i = 0; i < sizeX; i++)
  {
    for(j = 0; j < sizeY; j++)
    {
      for(k = 0; k < sizeTheta; k++)
      {
        if(poseWorld.poseActivity[i].array2D[j][k] > 0) //if cell active
        {
        	float thisActivation = poseWorld.poseActivity[i].array2D[j][k];
        	for (relX = -influenceXY; relX <= influenceXY; relX++)
        	{
            char neighbourX = getWrappedX(i + relX);
            for(relY = - influenceXY; relY<= influenceXY; relY++)
            {
              char neighbourY = getWrappedY(j + relY);
              for(relTheta = -influenceTheta; relTheta <= influenceTheta; relTheta++)
              {
                char neighbourTheta = getWrappedTheta(k + relTheta);
              	float excitationWeight = excitation_Weights[relX + influenceXY].array2D[relY + influenceXY][relTheta + influenceTheta];
                tempPose[neighbourX].array2D[neighbourY][neighbourTheta] += (thisActivation * excitationWeight * stepSize);
              }
            }
        	}
        }
      }
    }
  }
  memcpy(poseWorld.poseActivity, tempPose, numberOfCells); //fillFinalPose();
}

//----Inhibits neighbouring cells----//
float doInhibition(float stepSize)
{
	float inhibition = globalInhibition * stepSize;
  float activationSum = 0;
  numActive = 0; //clear number of active cells counter

  //initialise loop variable
  char i;
  char j;
  char k;

  for(i = 0; i < sizeX; i++)
  {
    for(j = 0; j < sizeY; j++)
    {
      for(k = 0; k < sizeTheta; k++)
      {
        if(poseWorld.poseActivity[i].array2D[j][k] > 0) //if cell active
        {
        	float activation = poseWorld.poseActivity[i].array2D[j][k] - inhibition;
          if(activation <=0)
          {
            activation = 0; //cant have negative activity
          }
          setActivation(i, j, k, activation); //set activation and see if is maximum
          activationSum += activation;
          if(activation>0)
          {
            numActive++; //increase number of active cells
          }
        }
      }
    }
  }
  return activationSum;
}

//----Normalises the activity in the pose matrix----//
void doNormalisation(float activationSum)
{//requires activationSum from inhibition

  //initalise loop variables
	char i;
  char j;
  char k;

  for(i = 0; i < sizeX; i++)
  {
    for(j = 0; j < sizeY; j++)
    {
      for(k = 0; k < sizeTheta; k++)
      {
        if(poseWorld.poseActivity[i].array2D[j][k] > 0) //if active
        {
        	poseWorld.poseActivity[i].array2D[j][k] = poseWorld.poseActivity[i].array2D[j][k] / activationSum; //normalise
        }
      }
    }
  }
}

//----Sets up the distribution for activity----//
void getActivationDistribution(float offsetX, float offsetY, float offsetTheta)
{
  //initialise variables
  char signX;
  char signY;
  char signTheta;
  float portion;

  char i;
  char j;
  char k;

  signX = -1;
  for(i = 0; i < 2; i++)
  {
    signY = -1;
    for(j = 0; j < 2; j++)
    {
      signTheta = -1;
      for(k = 0; k < 2; k++)
      {
        portion =  ((1-i) + signX * offsetX) * ((1-j) + signY * offsetY) * ((1-k) + signTheta * offsetTheta);
        distribution[i].array2D[j][k] = portion;
        signTheta = +1;
      }
      signY = +1;
    }
    signX = +1;
  }
}

//----Shifts the activity in the pose structure----//
void pathIntegrateCell(char xp, char yp, char thetap, float deltaTheta, float translation)
{
  //initialise loop variables
	char relativeX;
	char relativeY;
	char relativeTheta;

	char x;
	char y;
	char theta;

	float deltaPoseX = (cosDegrees(currentDirection) * translation) / 0.5;/// (lengthX / sizeX);
  float deltaPoseY = (sinDegrees(currentDirection) * translation) / 0.5; //(lengthX / sizeX);
	float deltaPoseTheta = deltaTheta / 60;//(360 / sizeTheta);

  int intOffsetX = (int) deltaPoseX; //only a whole number of cells moved
  int intOffsetY = (int) deltaPoseY;
  int intOffsetTheta = (int) deltaPoseTheta;

  getActivationDistribution(deltaPoseX - intOffsetX, deltaPoseY - intOffsetY, deltaPoseTheta - intOffsetTheta);

  for(relativeX = 0; relativeX < 2; relativeX++)
  {
  	x = getWrappedX(xp + intOffsetX + relativeX);
    for(relativeY = 0; relativeY < 2; relativeY++)
    {
      y = getWrappedY(yp + intOffsetY + relativeY);
    	for(relativeTheta = 0; relativeTheta < 2; relativeTheta++)
    	{
    	  theta = getWrappedTheta(thetap + intOffsetTheta + relativeTheta);
    	  tempPose[x].array2D[y][theta] += distribution[relativeX].array2D[relativeY][relativeTheta] * poseWorld.poseActivity[xp].array2D[yp][thetap];
    	}
    }
  }
}

//----Sets up Pose Cells----//
void initialisePose()
{
	setupPoseStructure();
  excitationMatrixSetup();
  startCell();
  numActive = 1;
}

//----handles all cell stuff----//
void iterate(float stepSize)
{
	float activeSum;
  doExcitation(stepSize);
  activeSum = doInhibition(stepSize);
  doNormalisation(activeSum);
}

//----handles pose thing----//
void pose3D(float deltaTheta, float translation)
{
  //initialise loop variables
  char i;
  char j;
  char k;
  memset(tempPose, 0, 2400); //a zero matrix to perform path integration on
  for(i = 0; i < 10; i++)
  {
    for(j = 0; j < 10; j++)
    {
      for(k = 0; k < 6; k++)
      {
        if(poseWorld.poseActivity[i].array2D[j][k] > 0) //if active
        {
          pathIntegrateCell(i, j, k, deltaTheta, translation);
        }
      }
    }
  }
  memcpy(poseWorld.poseActivity,tempPose,numberOfCells);
  iterate(stepSize);
}

//----Display Max Activated cell----//
void displayMax()
{
	char tempX, tempY, tempTheta;
  tempX = (char) poseWorld.maxActivatedCell.x;
  tempY = (char) poseWorld.maxActivatedCell.y;
  tempTheta = (char) poseWorld.maxActivatedCell.theta;
	eraseDisplay();
  nxtDisplayTextLine(1, "pose: %2d,%2d", tempX, tempY);
  nxtDisplayStringAt(68, 55, ",%2d", tempTheta);
}

//----test drives----//
void drive(char synchRatio, int travelDistance, char speed)
{
	//note a 90 degree turn is ~190 encoders clicks
	clearEncoders();
	nSyncedMotors = synchBC;
	nSyncedTurnRatio = synchRatio;
	nMotorPIDSpeedCtrl[motorB] = mtrEncoderReg;
	//nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;
  nMotorEncoderTarget[motorB] = travelDistance;
	motor[motorB] = speed;
  while(nMotorRunState[motorB] != runStateIdle) {}
  changeTheta = getRotation();
  currentDirection += changeTheta;
  if(currentDirection > 360)
  {
  	currentDirection -= 360;
  }
  else if(currentDirection < 0)
  {
  	currentDirection += 360;
  }
}

void drawRect(char xCo, char yCo, char percent)
{
  char startX = xCo * 6 + 2;
  char startY = yCo * 6 + 2;
  if(percent == 100)
  {
    nxtFillRect(startX, startY, startX + 5, startY + 5);
  }
  else if(percent == 85)
  {
  	int count = 0;
    char yOffset = 0;
    char xOffset = 0;
    while(count<6)
    {
      char x;

      for(x = 0; x<6; x++)
      {
      if(eightyFivePercent[x+xOffset]==1)
      {
         nxtSetPixel(startX+x, startY + yOffset);
        }

      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }

  }
  else if(percent == 75)
  {
    int count = 0;
    char yOffset = 0;
    char xOffset = 0;
    while(count<6)
    {
      char x;

      for(x = 0; x<6; x++)
      {
      if(seventyFivePercent[x+xOffset]==1)
      {
         nxtSetPixel(startX+x, startY + yOffset);
        }

      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }
  }
  else if(percent == 67)
  {
  	int count = 0;
   char yOffset = 0;
   char xOffset = 0;
   while(count<6)
   {
      char x;

      for(x = 0; x<6; x++)
      {
      if(sixtySevenPercent[x+xOffset]==1)
      {
         nxtSetPixel(startX+x, startY + yOffset);
        }

      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }
  }
  else if(percent == 50)
  {
   int count = 0;
   char yOffset = 0;
   char xOffset = 0;
   while(count<6)
   {
      char x;

      for(x = 0; x<6; x++)
      {
      if(fiftyPercent[x+xOffset]==1)
      {
         nxtSetPixel(startX+x, startY + yOffset);
      }

      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }
  }
  else if(percent == 33)
  {
  	int count = 0;
    char yOffset = 0;
    char xOffset = 0;
    while(count<6)
    {
      char x;

      for(x = 0; x<6; x++)
      {
      if(thirtyThreePercent[x+xOffset]==1)
      {
         nxtSetPixel(startX+x, startY + yOffset);
      }

      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }
  }
  else if(percent == 25)
  {
  	int count = 0;
    char yOffset = 0;
    char xOffset = 0;
    while(count<6)
    {
      char x;

      for(x = 0; x<6; x++)
      {
        if(twentyfivePercent[x+xOffset]==1)
        {
           nxtSetPixel(startX+x, startY + yOffset);
        }
      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }
  }
  else if(percent == 15)
  {
  	int count = 0;
    char yOffset = 0;
    char xOffset = 0;
    while(count<6)
    {
      char x;

      for(x = 0; x<6; x++)
      {
        if(fifteenPercent[x+xOffset]==1)
        {
          nxtSetPixel(startX+x, startY + yOffset);
        }
      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }
  }
  else if(percent == 2)
  {
  	int count = 0;
    char yOffset = 0;
    char xOffset = 0;
    while(count<6)
    {
      char x;

      for(x = 0; x<6; x++)
      {
        if(twoPercent[x+xOffset]==1)
        {
          nxtSetPixel(startX+x, startY + yOffset);
        }
      }
      xOffset += 6;
      yOffset+=1;
      count+=1;
    }
  }
}

//                            //
//----Local View Functions----//
//                            //

//----Initialises the arrays to zero----//
void clearTemp()
{
  memset(localTemp, 0, 4*numNeuralUnits); //sets entire array to zero
  memset(localComparison, 0, 4*numNeuralUnits); //sets entire array to zero
}

//----Writes the initial data----//
void writeLocal()
{
	CloseAllHandles(nIoResult);
	OpenWrite(hFileHandle,nIoResult,sFileName1,nFileSize);
	char x;
  for(x = 0; x<numNeuralUnits; x++)
  {
    WriteFloat(hFileHandle, nIoResult, localTemp.localArray[x]);
  }
  WriteByte(hFileHandle, nIoResult, poseWorld.maxActivatedCell.x);
  WriteByte(hFileHandle, nIoResult, poseWorld.maxActivatedCell.y);
  WriteByte(hFileHandle, nIoResult, poseWorld.maxActivatedCell.theta);
  Close(hFileHandle,nIoResult);
}

//----handles the storage of data----//
void swapFiles()
{
	OpenWrite(hFileHandle2,nIoResultRead,sFileName2,nFileSize2);
	OpenRead(hFileHandle,nIoResult,sFileName1,nFileSize);
	float tempVar;
	char tempX, tempY, tempTheta, z;
  while(nIoResult != ioRsltEndOfFile)
  {
  	for(z = 0; z<numNeuralUnits; z++)
  	{
      ReadFloat(hFileHandle,nIoResult,tempVar);
      if(nIoResult == ioRsltEndOfFile) {break;}
      WriteFloat(hFileHandle2,nIoResultRead,tempVar);
    }
    if(nIoResult == ioRsltEndOfFile) {break;}
    ReadByte(hFileHandle, nIoResult, tempX);
    ReadByte(hFileHandle, nIoResult, tempY);
    ReadByte(hFileHandle, nIoResult, tempTheta);
    WriteByte(hFileHandle2,nIoResultRead,tempX);
    WriteByte(hFileHandle2,nIoResultRead,tempY);
    WriteByte(hFileHandle2,nIoResultRead,tempTheta);
  }
	char x;
  for(x = 0; x<numNeuralUnits; x++)
  {
    WriteFloat(hFileHandle2, nIoResult, localTemp.localArray[x]);
  }
  WriteByte(hFileHandle2, nIoResult, poseWorld.maxActivatedCell.x);
  WriteByte(hFileHandle2, nIoResult, poseWorld.maxActivatedCell.y);
  WriteByte(hFileHandle2, nIoResult, poseWorld.maxActivatedCell.theta);
  Close(hFileHandle2,nIoResultRead);
  Close(hFileHandle,nIoResult);
  Delete(sFileName1,nIoResult);
  Rename(sFileName1,nIoResult,sFileName2);
}

//----Set the right neural units----//
void setRight(float rightSonarValue)
{
	//This function allocates a proportion to each neural unit based on the value returned by the sonar sensor
	//rightSonarValue = SensorValue(rightSonar);
	float tempCalc = 0;
	if(rightSonarValue <= firstUnit)
	{
		tempCalc = (float) (((firstUnit - rightSonarValue)/firstUnit));
    localTemp.localArray[12] = (float) 1 - tempCalc;
	}
  else if(rightSonarValue > firstUnit && rightSonarValue <= secondUnit)
  {
  	tempCalc = (float) (secondUnit - rightSonarValue)/(secondUnit - firstUnit);
    localTemp.localArray[12] = tempCalc;
  	localTemp.localArray[13] = 1 - tempCalc;
  }
  else if(rightSonarValue > secondUnit && rightSonarValue <= thirdUnit)
  {
  	tempCalc = (float) (thirdUnit - rightSonarValue)/(thirdUnit - secondUnit);
    localTemp.localArray[13] = tempCalc;
  	localTemp.localArray[14] = 1 - tempCalc;
  }
  else if(rightSonarValue > thirdUnit && rightSonarValue <= fourthUnit)
  {
  	tempCalc = (float) (fourthUnit - rightSonarValue)/(fourthUnit - thirdUnit);
    localTemp.localArray[14] = tempCalc;
  	localTemp.localArray[15] = 1 - tempCalc;
  }
  else if(rightSonarValue > fourthUnit && rightSonarValue <= fifthUnit)
  {
  	tempCalc = (float) (fifthUnit - rightSonarValue)/(fifthUnit - fourthUnit);
    localTemp.localArray[15] = tempCalc;
  	localTemp.localArray[16] = 1 - tempCalc;
  }
  else if(rightSonarValue > fifthUnit && rightSonarValue <= sixthUnit)
  {
  	tempCalc = (float) (sixthUnit - rightSonarValue)/(sixthUnit - fifthUnit);
    localTemp.localArray[16] = tempCalc;
  	localTemp.localArray[17] = 1 - tempCalc;
  }
  else if(rightSonarValue > sixthUnit) //if greater than 195cm
  {
    localTemp.localArray[17] = 1;
  }
}

//----Set centre neural units----//
void setCentre(float centreSonarValue)
{
	//This function allocates a proportion to each neural unit based on the value returned by the sonar sensor
	//centreSonarValue = SensorValue(centreSonar);
	float tempCalc = 0;
	if(centreSonarValue <= firstUnit)
	{
		tempCalc = (float) (((firstUnit - centreSonarValue)/firstUnit));
    localTemp.localArray[6] = (float) 1 - tempCalc;
	}
  else if(centreSonarValue > firstUnit && centreSonarValue <= secondUnit)
  {
  	tempCalc = (float) (secondUnit - centreSonarValue)/(secondUnit - firstUnit);
    localTemp.localArray[6] = tempCalc;
  	localTemp.localArray[7] = 1 - tempCalc;
  }
  else if(centreSonarValue > secondUnit && centreSonarValue <= thirdUnit)
  {
  	tempCalc = (float) (thirdUnit - centreSonarValue)/(thirdUnit - secondUnit);
    localTemp.localArray[7] = tempCalc;
  	localTemp.localArray[8] = 1 - tempCalc;
  }
  else if(centreSonarValue > thirdUnit && centreSonarValue <= fourthUnit)
  {
  	tempCalc = (float) (fourthUnit - centreSonarValue)/(fourthUnit - thirdUnit);
    localTemp.localArray[8] = tempCalc;
  	localTemp.localArray[9] = 1 - tempCalc;
  }
  else if(centreSonarValue > fourthUnit && centreSonarValue <= fifthUnit)
  {
  	tempCalc = (float) (fifthUnit - centreSonarValue)/(fifthUnit - fourthUnit);
    localTemp.localArray[9] = tempCalc;
  	localTemp.localArray[10] = 1 - tempCalc;
  }
  else if(centreSonarValue > fifthUnit && centreSonarValue <= sixthUnit)
  {
  	tempCalc = (float) (sixthUnit - centreSonarValue)/(sixthUnit - fifthUnit);
    localTemp.localArray[10] = tempCalc;
  	localTemp.localArray[11] = 1 - tempCalc;
  }
  else if(centreSonarValue > sixthUnit)
  {
    localTemp.localArray[11] = 1;
  }
}

//----set left neural units----//
void setLeft(float leftSonarValue)
{
	//This function allocates a proportion to each neural unit based on the value returned by the sonar sensor
	//leftSonarValue = SensorValue(leftSonar);
	float tempCalc = 0;
	if(leftSonarValue <= firstUnit)
	{
		tempCalc = (float) (((firstUnit - leftSonarValue)/firstUnit));
    localTemp.localArray[0] = (float) 1 - tempCalc;
	}
  else if(leftSonarValue > firstUnit && leftSonarValue <= secondUnit)
  {
  	tempCalc = (float) (secondUnit - leftSonarValue)/(secondUnit - firstUnit);
    localTemp.localArray[0] = tempCalc;
  	localTemp.localArray[1] = 1 - tempCalc;
  }
  else if(leftSonarValue > secondUnit && leftSonarValue <= thirdUnit)
  {
  	tempCalc = (float) (thirdUnit - leftSonarValue)/(thirdUnit - secondUnit);
    localTemp.localArray[1] = tempCalc;
  	localTemp.localArray[2] = 1 - tempCalc;
  }
  else if(leftSonarValue > thirdUnit && leftSonarValue <= fourthUnit)
  {
  	tempCalc = (float) (fourthUnit - leftSonarValue)/(fourthUnit - thirdUnit);
    localTemp.localArray[2] = tempCalc;
  	localTemp.localArray[3] = 1 - tempCalc;
  }
  else if(leftSonarValue > fourthUnit && leftSonarValue <= fifthUnit)
  {
  	tempCalc = (float) (fifthUnit - leftSonarValue)/(fifthUnit - fourthUnit);
    localTemp.localArray[3] = tempCalc;
  	localTemp.localArray[4] = 1 - tempCalc;
  }
  else if(leftSonarValue > fifthUnit && leftSonarValue <= sixthUnit)
  {
  	tempCalc = (float) (sixthUnit - leftSonarValue)/(sixthUnit - fifthUnit);
    localTemp.localArray[4] = tempCalc;
  	localTemp.localArray[5] = 1 - tempCalc;
  }
  else if(leftSonarValue > sixthUnit)
  {
    localTemp.localArray[5] = 1;
  }
}


//----Dot multiply two vectors----//
float dotMultiply()
{
  char i;
  float dotValue = 0;
  for(i = 0; i < numNeuralUnits; i++)
  {
    if(localTemp.localArray[i]>0)
    {
      dotValue = dotValue + localTemp.localArray[i] * localComparison.localArray[i];
    }
  }
  return dotValue; //return the multiply
}

//----normalise the current view for processing----//
void normaliseTemp()
{
//will normalise the temp ||a|| = sqrt(a1^2 + a2^2 + a3^3)
//normalise by a/||a||
	float tempTotal = 0;
	char y;
	for(y = 0; y < numNeuralUnits; y++)
	{
		if(localTemp.localArray[y]>0) //only if over zero spend clock cycles
		{
		  tempTotal = tempTotal + localTemp.localArray[y]*localTemp.localArray[y]; //a.a
	  }
	}
	tempTotal = sqrt(tempTotal); //sqrt(a.a)
	for(y = 0; y < numNeuralUnits; y++)
	{
		if(localTemp.localArray[y]>0)
		{
	    localTemp.localArray[y] = (float) localTemp.localArray[y]/tempTotal;
	  }
	}
}

//----Gets local view and processes ready for comparison----//
void setTemp()
{
	//initalises temp, get sensor readings and sets the local temp to a normalised neural vector
  clearTemp();
	float rightSonarValue = SensorValue(rightSonar); //obvious
  float leftSonarValue = SensorValue(leftSonar);
  float centreSonarValue = SensorValue(centreSonar);
  setLeft(leftSonarValue);
	setCentre(centreSonarValue);
	setRight(rightSonarValue);
	normaliseTemp();
}

//----Checks if there is a match, add activities, else creates a new association----//
void checkLocalCell()
{
	//uses a normalised version of the localTemp.  The comparison local cells are stored as normalised when 1st created
	char z;
	char breakSymbol =0;
	signed char cellCount = 0;
	char match = 0;
	float dotTempValue = 0;
	float tempAngle = 0;
	if(nextEmptyCell == 0)
	{
	  //first localCellView
		writeLocal();
    nextEmptyCell++;
    PlaySound(soundFastUpwardTones);
    while(bSoundActive) {}
	}
  else {
  OpenRead(hFileHandle3,nIoResultRead,sFileName1,nFileSize);
  while(nIoResultRead != ioRsltEndOfFile)
    {
    	//search for a previous local cell that matches the current view to a certain degree
    	for(z = 0; z<numNeuralUnits; z++)
    	{
    		ReadFloat(hFileHandle3,nIoResultRead,localComparison.localArray[z]);
    		if(nIoResultRead == ioRsltEndOfFile) {breakSymbol = 1;break;}
    	}
    	if(breakSymbol == 1) {break;}
      ReadByte(hFileHandle3, nIoResultRead, injectX);
      ReadByte(hFileHandle3, nIoResultRead, injectY);
      ReadByte(hFileHandle3, nIoResultRead, injectTheta);

      dotTempValue = dotMultiply();
      tempAngle = acos(dotTempValue);
      if(tempAngle<0.17)//0.17 //if difference less than 10 degrees between vectors
      {
      	match = 1;
      	Close(hFileHandle3,nIoResultRead);
      	break; //save cycles break out
      }
      cellCount++;
    }
    if(match == 0)
    {//no match found - create a new local view cell
      Close(hFileHandle3,nIoResultRead);
      swapFiles();
    	nextEmptyCell++;
      PlaySound(soundFastUpwardTones);
      while(bSoundActive) {}
    }
    else if(match == 1)
    {
    	injectEnergy(stepSize, injectX, injectY, injectTheta);
    	nxtDisplayStringAt(64,30,"x: %2d",injectX);
	    nxtDisplayStringAt(64,20,"y: %2d",injectY);
	    nxtDisplayStringAt(64,10,"T: %1d",injectTheta);
      PlaySound(soundBeepBeep);
      while(bSoundActive) {}
    }
  }
}

//----Turns if need to----//
void doTurn()
{
//part of the testing reigme of the local cells
	//decided that anticlockwise is positive
	float rightSonarValue = SensorValue(rightSonar); //obvious
  float leftSonarValue = SensorValue(leftSonar);
  float centreSonarValue = SensorValue(centreSonar);


	if(centreSonarValue<19)
	{
	  if(leftSonarValue > 19 && rightSonarValue < 19)
	  {
      drive(100,190,-50);
      drive(-100,190,-50);
	  }
		else if(leftSonarValue < 19 && rightSonarValue > 19)
	  {
	  	drive(100,190,-50);
	    drive(-100,190,50);
	  }
		else if(leftSonarValue < 19 && rightSonarValue < 19)
	  {
	  	drive(100,190,-50);
	  	drive(-100,370,50);
	   }
	  else
	  {
	  	drive(100,190,-50);
      drive(-100,190,-50);
	  }
  }
}

//----Logs data - for testing only----//
void datalogging()
{
	char tempX, tempY, tempTheta;
  tempX = (char) poseWorld.maxActivatedCell.x;
  tempY = (char) poseWorld.maxActivatedCell.y;
  tempTheta = (char) poseWorld.maxActivatedCell.theta;
	AddToDatalog(1,tempX);
  AddToDatalog(2,tempY);
  AddToDatalog(3,tempTheta);
  AddToDatalog(4,numActive);
  AddToDatalog(5,'0'); //just a separator
}

void sumPoseStruct()
{
  float tempStruct[10][10];
  memset(tempStruct,0,400);
  char x,y,z;
  float sumActive = 0;
  for(x = 0; x<10; x++)
  {
    for(y=0; y<10; y++)
    {
      for(z=0; z<6; z++)
      {
        tempStruct[x][y] += poseWorld.poseActivity[x].array2D[y][z];
      }
    }
  }
  sumActive = tempStruct[poseWorld.maxActivatedCell.x][poseWorld.maxActivatedCell.y];
  eraseDisplay();
  nxtDrawRect(1,1,62,62);
  nxtDisplayStringAt(64,60,"x: %2d",poseWorld.maxActivatedCell.x);
	nxtDisplayStringAt(64,50,"y: %2d",poseWorld.maxActivatedCell.y);
	nxtDisplayStringAt(64,40,"T: %1d",poseWorld.maxActivatedCell.theta);
  for(x = 0; x<10; x++)
  {
    for(y = 0; y<10; y++)
    {
      char tempPercent = 0;
      tempPercent = (tempStruct[x][y] / sumActive)*100;
      if(tempPercent<=2) {}
      else if(tempPercent>2 && tempPercent<=7)
      {
        drawRect(x,y,2);
      }
      else if(tempPercent>7 && tempPercent<=15)
      {
        drawRect(x,y,15);
      }
      else if(tempPercent>15 && tempPercent<=25)
      {
        drawRect(x,y,25);
      }
      else if(tempPercent>25 && tempPercent<=33)
      {
        drawRect(x,y,33);
      }
      else if(tempPercent>33 && tempPercent<=50)
      {
        drawRect(x,y,50);
      }
      else if(tempPercent>50 && tempPercent<=66)
      {
        drawRect(x,y,66);
      }
      else if(tempPercent>66 && tempPercent<=75)
      {
        drawRect(x,y,75);
      }
      else if(tempPercent>75 && tempPercent<=97)
      {
        drawRect(x,y,85);
      }
      else if(tempPercent>97 && tempPercent<=100)
      {
        drawRect(x,y,100);
      }
    }
  }
}
//                  //
//----Experience----//
//                  //
void createNewExperience(experience &newE)
{
  //going to assume everytime a createNewExperience is called it will affect the Map.currentExperience experience cell
	memset(newE,0,112);
	char temp[5] = {-1,-1,-1,-1,-1}; //My null symbol
	newE.mapPose.x = -1; //null - not yet set up
	newE.ID = nextID;
	memcpy(newE.outLinks,temp,10); //initalise to null
  memcpy(newE.inLinks,temp,10);
	memcpy(newE.odoPose,encoderData,6);
	memcpy(newE.poseCellsPose,poseWorld.maxActivatedCell,3);
	memcpy(newE.localView,localTemp,72);
}

//----Sets Outlinks and Inlinks----//
void setOutlinks(char linkID, experience &startE, experience &endE)
{
	char t; //for loop
	for(t = 0; t<numOfLinksPerExperience; t++)
	{
	  if(startE.outLinks[t] == -1)//an empty link
	  {
	  	startE.outLinks[t] = linkID;
	  	break;
	  }
	}
	for(t = 0; t<numOfLinksPerExperience; t++)
	{
		if(endE.inLinks[t] == -1)//an empty link
	  {
	  	endE.inLinks[t] = linkID;
	  	break;
	  }

	}
}

//Due to various information being needed to calculate the link it is necessary to create the temp experience
// 'currentExperience' and insert it into the experience map once a new experience becomes active
// the linkLastToCurrent performs the linking - with the linkExperience calling that and setting up a new temp
// experience
void linkLastToCurrent() //note:- trying char for now to try and cut memory problems
{
  int currentMeanTime = (Map.currentExperienceStartTime + (nPgmTime/1000)) / 2;

  if(Map.lastMatchedExperienceID != -1) //therefore not null
  {
  	//time taken for transistion
  	char transitionTime = currentMeanTime - Map.lastExperienceMeanTime; //shouldnt be more than 128 seconds for transistion

  	//Set up pose info and copy data into
    vector3D currentOdoPose;
    memcpy(currentOdoPose, Map.currentExperience.odoPose,6); // may need to memcpy
    vector3D lastOdoPose;
    memcpy(lastOdoPose,Map.experienceMap[Map.lastMatchedExperienceID].odoPose,6); //same as above

    //angle to current (angle = atan(y/x))
    float angleToCurrent = getAngleDegrees((currentOdoPose.x - lastOdoPose.x),(currentOdoPose.y - lastOdoPose.y));
    float translationAngle = lastOdoPose.theta - angleToCurrent;

    //translation distance (in encoder clicks)
    int translationDistance = getLength((currentOdoPose.x - lastOdoPose.x),(currentOdoPose.y - lastOdoPose.y));

    //relative change in rotation
    float rotation = getRotationDegrees(lastOdoPose.theta, currentOdoPose.theta);

    //therefore has not been inserted onto experience map yet
    if(Map.currentExperience.mapPose.x == -1) //null statement
    {
      vector3D lastMapPose;
      vector3D newMapPose;
      memcpy(lastMapPose, Map.experienceMap[Map.lastMatchedExperienceID].mapPose, 6);

      float calcsAngle = lastMapPose.theta + translationAngle;
      newMapPose.x = (lastMapPose.x + cosDegrees(calcsAngle) * translationDistance);
      newMapPose.y = (lastMapPose.y + sinDegrees(calcsAngle) * translationDistance);
      newMapPose.theta = (lastMapPose.theta + rotation);
      memcpy(Map.currentExperience.mapPose, newMapPose, 6); //set up mapPose for current Experience
      memcpy(Map.experienceMap[Map.currentExperience.ID], Map.currentExperience, 112); //put currentExperience on the map
    }
    char y;
    int linkNumber;
    for(y = 0; y<5; y++)
    {
      linkNumber = Map.experienceMap[Map.lastMatchedExperienceID].outLinks[y];
    	if(linkNumber != -1)
    	{
    	  if(links[linkNumber].endExperienceID == Map.currentExperience.ID)
    	  {
    	    break; //using linkNumber
    	  }
    	}
    	linkNumber = -1;
    }
    //if no link
    if(linkNumber == -1)
    {
    	//create new link with all data needed
      experienceLink link;
    	link.startExperienceID = Map.lastMatchedExperienceID;
    	link.endExperienceID = Map.currentExperience.ID;
    	link.transitionTime = transitionTime;
    	link.translationAngle = translationAngle;
    	link.translationDistance = translationDistance;
    	link.rotation = rotation;
    	memcpy(links[nextLink],link,12);
    	setOutlinks(nextLink, Map.experienceMap[Map.lastMatchedExperienceID],Map.experienceMap[Map.currentExperience.ID]); //sets the outlinks and inlinks
    	nextLink++; //increment new link
    }
    //else if link existes, update
    else
    {
      experienceLink previous;
      memcpy(previous,links[linkNumber],12);
      previous.transitionTime = (previous.transitionTime + transitionTime) / 2;
      previous.translationAngle = (previous.translationAngle + translationAngle) / 2;
      previous.translationDistance = (previous.translationDistance + translationDistance) / 2;
      previous.rotation = (previous.rotation + rotation) / 2;
      memcpy(links[linkNumber], previous,12);
    }
  }

  //set current as previous experience
  Map.lastMatchedExperienceID = Map.currentExperience.ID;
  Map.lastExperienceMeanTime = currentMeanTime;
}


void linkExperience(experience &cExperience)
{
  linkLastToCurrent();
	memcpy(Map.currentExperience, cExperience, 112); //add experience
  Map.currentExperienceStartTime = (int) (nPgmTime/1000); //in seconds
}


//sets links --------------may need fixing
void setLink(int startID, int endID)
{
  links[nextLink].startExperienceID = startID;
  links[nextLink].endExperienceID = endID;
}

//----Compares arrays - this is due to RobotC unable to do this----//
char compareArray(localViewCell &view1, localViewCell &view2)
{
	float array1[18], array2[18], nullArray[18];
	memset(nullArray, 0, 72);
	memcpy(array1, view1, 72);
	memcpy(array2, view2, 72);

	char x;
	char check = 0;
	for(x = 0; x<18; x++)
	{
		if(array1[x] != nullArray[x])
		{
		  check = 1; // not a null vector
		  break;
		}
	}
	if(check)
	{
		for(x = 0; x<18; x++)
	  {
		  if(array1[x] != array2[x])
		  {
		    return 0; // not a null vector
		  }
		}
		return 1;
	}
	else {return 0;}
}

//----Compares two Experiences----//
float compareTo(experience &experience1, experience &experience2)
{
  //first test
	char firstTest = compareArray(experience1.localView,experience2.localView);
	if(!firstTest)
	{
	  return 0;
	}

	//2nd test
	vector3D thisPose;
	vector3D otherPose;
	memcpy(thisPose, experience1.poseCellsPose, 6);
	memcpy(otherPose, experience2.poseCellsPose, 6);
  char thetaAbsDist = abs(thisPose.theta - otherPose.theta);
  if(thetaAbsDist > maxAssociationRadiusTheta)
  {
    return 0;
  }

  //3rd test
  float maxXYDistSquared = maxAssociationRadiusXY * maxAssociationRadiusXY;
  int xyDistSquared = ((otherPose.x - thisPose.x) * (otherPose.x - thisPose.x)) +
                        ((otherPose.y - thisPose.y) * (otherPose.y - thisPose.y));
  if(xyDistSquared > maxXYDistSquared)
  {
    return 0;
  }

  //otherwise is a measure of comparison from 0 to 1 comprised of a 0.5 contribution from theta and xy respectively
  return (2 - (sqrt(xyDistSquared) / maxAssociationRadiusXY) -
                  (thetaAbsDist / maxAssociationRadiusTheta)) * 0.5;

}

//this compares the current experience to previous experiences returning the closest matching experience
//returning the array id of the closest experience.
int matchExperience(experience &matchE)
{
  float maxScore = 0;
  int closestMatch = -1;
	char x;
	for(x = 0; x<nextID; x++)
	{
		float score = compareTo(matchE,Map.experienceMap[x]);
		if(score > maxScore)
		{
		  	closestMatch = x;
		  	maxScore = score;
		}

	}
	return closestMatch;
}

//----Corrects the Experience Map----//
//So far have used floats but as all structs use ints i may be able to get away with not using floats at all. Yay to the memory savings
void mapCorrection()
{
	float mapCorrectionXY = mapCorrectionRateXY * 0.5;
	float mapCorrectionTheta = mapCorrectionRateTheta * 0.5;

	experience startExperience;
	experience endExperience;
	vector3D startPose;
	vector3D endPose;
	experienceLink link;

	char z; //for loop
	for(z = 0; z <(nextID-1); z++)
	{
		memcpy(startExperience,Map.experienceMap[z],110); //copy experience being manipulated into startExperience
		memcpy(startPose, startExperience.mapPose, 6); //copy mapPose being manipulated into startPose
    char y; //for loop
    for(y = 0; y < numOfLinksPerExperience; y++)
    {
      if(startExperience.outLinks[y] != -1)
      {
        memcpy(link,links[startExperience.outLinks[y]],12);
        memcpy(endExperience,Map.experienceMap[link.endExperienceID],110);
        memcpy(endPose, endExperience.mapPose, 6);

        //expected position of the end experience
        float angleToTargetEnd = startPose.theta + link.translationAngle;
        float targetEndX = startPose.x + link.translationDistance * cosDegrees(angleToTargetEnd);
        float targetEndY = startPose.y + link.translationDistance * sinDegrees(angleToTargetEnd);

        //expected orientation of the end experience
        float targetEndAngle = startPose.theta + link.rotation;

        //Calulate the 'error' between expected and actual position of end experience
        float xError = targetEndX - endPose.x;
        float yError = targetEndY - endPose.y;
        float thetaError = getRotationDegrees(endPose.theta,targetEndAngle);

        //calculate the adjustment to be made for start and end poses
        float xAdjustment = xError * mapCorrectionXY;
        float yAdjustment = yError * mapCorrectionXY;
        float thetaAdjustment = thetaError * mapCorrectionTheta;

        //Apply adjustments then copy back over previous experiences
        startPose.x -= xAdjustment;
        startPose.y -= yAdjustment;
        startPose.theta = wrappedDegrees360(startPose.theta - thetaAdjustment);

        endPose.x += xAdjustment;
        endPose.y += yAdjustment;
        endPose.theta = wrappedDegrees360(endPose.theta + thetaAdjustment);

        memcpy(startExperience.mapPose, startPose, 6);
        memcpy(Map.experienceMap[z], startExperience, 110);

        memcpy(endExperience.mapPose, endPose, 6);
        memcpy(Map.experienceMap[link.endExperienceID],endExperience,110);
      }
      else {break;} //leave loop faster as there are no more links
    }
  }
}

//----creates the first experience----//
void startUp()
{
	experience startUpExperience;
  createNewExperience(startUpExperience);
  startUpExperience.mapPose.x = 0;
  startUpExperience.mapPose.y = 0;
  startUpExperience.mapPose.theta = 0;
  memcpy(Map.currentExperience,startUpExperience,112);
  Map.currentExperienceStartTime = (int) (nPgmTime/1000);
  //this is my addition - i couldn't find in the java code where the first current view was create placed on the experience map
  memcpy(Map.experienceMap[nextID],Map.currentExperience,112);
  Map.lastMatchedExperienceID = 0;
  nextID++;
}

void iterateMap(float stepSize)
{
  experience newExperience;
  createNewExperience(newExperience);
  int closestExperience = matchExperience(newExperience);

  if(closestExperience != -1)
  {
    if(closestExperience != nextID)
    {
    	experience closeExperience;
    	memcpy(closestExperience,Map.experienceMap[closestExperience],112);
    	linkExperience(closeExperience);
    }
  }
  else
  {
    linkExperience(newExperience);
    nextID++;
  }
}

void initaliseMap()
{
	memset(Map,0,678);
	Map.lastMatchedExperienceID = -1;
	memset(Links,0,60);
  memset(encoderData,0,6);
}


//----main----//
task main ()
{
	Delete(sFileName1, nIoResult);
	Delete(sFileName2, nIoResult);
	nxtDisplayCenteredTextLine(3, "Roaming");
	nxtDisplayCenteredTextLine(5, "This is a test");
	initialisePose(); //set up
	iterate(stepSize); //run excitation etc
	currentDirection = 0; //set initial
  currentTheta = 0;
  setTemp();  //get local view
  checkLocalCell(); //create first association

  datalogging();
  sumPoseStruct();
	while(1)
	{
		alive(); //stop NXT from sleeping

    float centreSonarValue = SensorValue(centreSonar);
    if(centreSonarValue<19)
	  {
	  	doTurn();
	  	pose3D(changeTheta,0);
	  }
	  else {
	  drive(100,180,50);
    pose3D(changeTheta,0.5);
    }
    sumPoseStruct();
    setTemp();
    checkLocalCell();

    //store data
    datalogging();
    clearEncoders(); //clear encoder count
    changeTheta=0;
  }
  SaveNxtDatalog();
  PlaySound(soundException);
  while(bSoundActive){}
}
